services:
  - docker

before_script: |
  docker pull wfu1218/devel-centos:centos7

script: |
  docker run --rm -it -v ${PWD}:/home wfu1218/devel-centos:centos7 sh -c ". ~/.bashrc; cd /home; make; make test"

after_script: |
  docker rmi wfu1218/devel-centos:centos7
