services:
  - docker

before_script: |
  docker pull centos:centos7
  docker build test/centos -t devel

script: |
  docker run --rm -it -v ${PWD}:/home devel sh -c ". ~/.bashrc; cd /home; make; make test"

after_script: |
  docker rmi devel-env
